name: CustomItem
version: 1.0.0
main: cwr.cutomIterm.Entity_Wand.EntityWandPlugin
api-version: '1.21'
commands:
  customitem:
    description: Manage custom items
    usage: /<command> [args]
    permission: customitem.use
  customrecipes:
    description: Open custom recipes GUI
    usage: /<command>
    permission: customrecipes.use
permissions:
  customitem.use:
    description: Use custom item commands
    default: true
  customitem.give:
    description: Give custom items
    default: op
  customitem.admin:
    description: Admin commands for custom items
    default: op
  customrecipes.use:
    description: Open custom recipes GUI
    default: true